<?php
/**
 * ShipmentPickupRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Boxture\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Boxture API v2
 *
 * Detailed documentation and test tool for the Boxture API v2
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@boxture.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Boxture\V2\Model;

use \ArrayAccess;
use \Boxture\V2\ObjectSerializer;

/**
 * ShipmentPickupRequest Class Doc Comment
 *
 * @category Class
 * @package  Boxture\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentPickupRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentPickupRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'pickedupAt' => '\DateTime',
        'waybillNr' => 'string',
        'waybillNrConfirmation' => 'string',
        'pickupCodeConfirmation' => 'string',
        'lines' => '\Boxture\V2\Model\ShipmentPickupLineRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'pickedupAt' => 'date',
        'waybillNr' => null,
        'waybillNrConfirmation' => null,
        'pickupCodeConfirmation' => null,
        'lines' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pickedupAt' => 'pickedup_at',
        'waybillNr' => 'waybill_nr',
        'waybillNrConfirmation' => 'waybill_nr_confirmation',
        'pickupCodeConfirmation' => 'pickup_code_confirmation',
        'lines' => 'lines'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pickedupAt' => 'setPickedupAt',
        'waybillNr' => 'setWaybillNr',
        'waybillNrConfirmation' => 'setWaybillNrConfirmation',
        'pickupCodeConfirmation' => 'setPickupCodeConfirmation',
        'lines' => 'setLines'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pickedupAt' => 'getPickedupAt',
        'waybillNr' => 'getWaybillNr',
        'waybillNrConfirmation' => 'getWaybillNrConfirmation',
        'pickupCodeConfirmation' => 'getPickupCodeConfirmation',
        'lines' => 'getLines'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pickedupAt'] = isset($data['pickedupAt']) ? $data['pickedupAt'] : null;
        $this->container['waybillNr'] = isset($data['waybillNr']) ? $data['waybillNr'] : null;
        $this->container['waybillNrConfirmation'] = isset($data['waybillNrConfirmation']) ? $data['waybillNrConfirmation'] : null;
        $this->container['pickupCodeConfirmation'] = isset($data['pickupCodeConfirmation']) ? $data['pickupCodeConfirmation'] : null;
        $this->container['lines'] = isset($data['lines']) ? $data['lines'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['waybillNr'] === null) {
            $invalidProperties[] = "'waybillNr' can't be null";
        }
        if ($this->container['waybillNrConfirmation'] === null) {
            $invalidProperties[] = "'waybillNrConfirmation' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pickedupAt
     *
     * @return \DateTime|null
     */
    public function getPickedupAt()
    {
        return $this->container['pickedupAt'];
    }

    /**
     * Sets pickedupAt
     *
     * @param \DateTime|null $pickedupAt Pickup date/time, you can leave this empty to use the current date/time
     *
     * @return $this
     */
    public function setPickedupAt($pickedupAt)
    {
        $this->container['pickedupAt'] = $pickedupAt;

        return $this;
    }

    /**
     * Gets waybillNr
     *
     * @return string
     */
    public function getWaybillNr()
    {
        return $this->container['waybillNr'];
    }

    /**
     * Sets waybillNr
     *
     * @param string $waybillNr Waybill number on shipment level (consult your channel settings). <br>Only needed when a waybill is needed for pickup (check handling options).
     *
     * @return $this
     */
    public function setWaybillNr($waybillNr)
    {
        $this->container['waybillNr'] = $waybillNr;

        return $this;
    }

    /**
     * Gets waybillNrConfirmation
     *
     * @return string
     */
    public function getWaybillNrConfirmation()
    {
        return $this->container['waybillNrConfirmation'];
    }

    /**
     * Sets waybillNrConfirmation
     *
     * @param string $waybillNrConfirmation Waybill number confirmation on shipment level (consult your channel settings).<br>Only needed when a waybill is know at pickup time.
     *
     * @return $this
     */
    public function setWaybillNrConfirmation($waybillNrConfirmation)
    {
        $this->container['waybillNrConfirmation'] = $waybillNrConfirmation;

        return $this;
    }

    /**
     * Gets pickupCodeConfirmation
     *
     * @return string|null
     */
    public function getPickupCodeConfirmation()
    {
        return $this->container['pickupCodeConfirmation'];
    }

    /**
     * Sets pickupCodeConfirmation
     *
     * @param string|null $pickupCodeConfirmation pickupCodeConfirmation
     *
     * @return $this
     */
    public function setPickupCodeConfirmation($pickupCodeConfirmation)
    {
        $this->container['pickupCodeConfirmation'] = $pickupCodeConfirmation;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return \Boxture\V2\Model\ShipmentPickupLineRequest[]|null
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param \Boxture\V2\Model\ShipmentPickupLineRequest[]|null $lines lines
     *
     * @return $this
     */
    public function setLines($lines)
    {
        $this->container['lines'] = $lines;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


