<?php
/**
 * HandlingUnitsApi
 * PHP version 5
 *
 * @category Class
 * @package  Boxture\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Boxture API v2
 *
 * Detailed documentation and test tool for the Boxture API v2
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@boxture.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Boxture\V2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Boxture\V2\ApiException;
use Boxture\V2\Configuration;
use Boxture\V2\HeaderSelector;
use Boxture\V2\ObjectSerializer;

/**
 * HandlingUnitsApi Class Doc Comment
 *
 * @category Class
 * @package  Boxture\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HandlingUnitsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getHandlingUnits
     *
     * List handling units
     *
     * @param  string $search search (optional)
     * @param  string $orderField Exact field name you want to sort the output by (optional)
     * @param  string $orderDirection Sort direction (optional, default to 'asc')
     * @param  int $page Page number (optional, default to 1)
     * @param  int $pageSize Max number of results per page (optional, default to 25)
     *
     * @throws \Boxture\V2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Boxture\V2\Model\HandlingUnitResponse|\Boxture\V2\Model\ErrorResponse|\Boxture\V2\Model\ErrorResponse
     */
    public function getHandlingUnits($search = null, $orderField = null, $orderDirection = 'asc', $page = 1, $pageSize = 25)
    {
        list($response) = $this->getHandlingUnitsWithHttpInfo($search, $orderField, $orderDirection, $page, $pageSize);
        return $response;
    }

    /**
     * Operation getHandlingUnitsWithHttpInfo
     *
     * List handling units
     *
     * @param  string $search (optional)
     * @param  string $orderField Exact field name you want to sort the output by (optional)
     * @param  string $orderDirection Sort direction (optional, default to 'asc')
     * @param  int $page Page number (optional, default to 1)
     * @param  int $pageSize Max number of results per page (optional, default to 25)
     *
     * @throws \Boxture\V2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Boxture\V2\Model\HandlingUnitResponse|\Boxture\V2\Model\ErrorResponse|\Boxture\V2\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHandlingUnitsWithHttpInfo($search = null, $orderField = null, $orderDirection = 'asc', $page = 1, $pageSize = 25)
    {
        $request = $this->getHandlingUnitsRequest($search, $orderField, $orderDirection, $page, $pageSize);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\Boxture\V2\Model\HandlingUnitResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Boxture\V2\Model\HandlingUnitResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Boxture\V2\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Boxture\V2\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Boxture\V2\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Boxture\V2\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Boxture\V2\Model\HandlingUnitResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boxture\V2\Model\HandlingUnitResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boxture\V2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Boxture\V2\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHandlingUnitsAsync
     *
     * List handling units
     *
     * @param  string $search (optional)
     * @param  string $orderField Exact field name you want to sort the output by (optional)
     * @param  string $orderDirection Sort direction (optional, default to 'asc')
     * @param  int $page Page number (optional, default to 1)
     * @param  int $pageSize Max number of results per page (optional, default to 25)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHandlingUnitsAsync($search = null, $orderField = null, $orderDirection = 'asc', $page = 1, $pageSize = 25)
    {
        return $this->getHandlingUnitsAsyncWithHttpInfo($search, $orderField, $orderDirection, $page, $pageSize)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHandlingUnitsAsyncWithHttpInfo
     *
     * List handling units
     *
     * @param  string $search (optional)
     * @param  string $orderField Exact field name you want to sort the output by (optional)
     * @param  string $orderDirection Sort direction (optional, default to 'asc')
     * @param  int $page Page number (optional, default to 1)
     * @param  int $pageSize Max number of results per page (optional, default to 25)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHandlingUnitsAsyncWithHttpInfo($search = null, $orderField = null, $orderDirection = 'asc', $page = 1, $pageSize = 25)
    {
        $returnType = '\Boxture\V2\Model\HandlingUnitResponse';
        $request = $this->getHandlingUnitsRequest($search, $orderField, $orderDirection, $page, $pageSize);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHandlingUnits'
     *
     * @param  string $search (optional)
     * @param  string $orderField Exact field name you want to sort the output by (optional)
     * @param  string $orderDirection Sort direction (optional, default to 'asc')
     * @param  int $page Page number (optional, default to 1)
     * @param  int $pageSize Max number of results per page (optional, default to 25)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getHandlingUnitsRequest($search = null, $orderField = null, $orderDirection = 'asc', $page = 1, $pageSize = 25)
    {
        if ($pageSize !== null && $pageSize > 100) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling HandlingUnitsApi.getHandlingUnits, must be smaller than or equal to 100.');
        }
        if ($pageSize !== null && $pageSize < 10) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling HandlingUnitsApi.getHandlingUnits, must be bigger than or equal to 10.');
        }


        $resourcePath = '/handling_units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search);
        }
        // query params
        if ($orderField !== null) {
            $queryParams['order_field'] = ObjectSerializer::toQueryValue($orderField);
        }
        // query params
        if ($orderDirection !== null) {
            $queryParams['order_direction'] = ObjectSerializer::toQueryValue($orderDirection);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($pageSize !== null) {
            $queryParams['page_size'] = ObjectSerializer::toQueryValue($pageSize);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
